FROM jenkins/inbound-agent:latest-jdk17

USER root

# Install dependencies and Terraform
# Combined RUN instruction to ensure apt-get update and install run in the same cache layer
RUN apt-get update && apt-get install -y \
    gnupg \
    # software-properties-common \
    curl \
    lsb-release
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list 
RUN apt-get update && apt-get install -y terraform \
    && rm -rf /var/lib/apt/lists/*

USER jenkins
